In [1]:
import pandas as pd
from wwo_hist import retrieve_hist_data

In [8]:
frequency = 3
start_date = '01-JAN-2010'
end_date = '01-JUN-2020'
api_key = 'da4fe6c3807244109b6191209201511'
location_list = ['baltimore']
hist_weather_data = retrieve_hist_data(api_key,
                                location_list,
                                start_date,
                                end_date,
                                frequency,
                                location_label = False,
                                export_csv = True,
                                store_df = True)

Retrieving weather data for baltimore


Currently retrieving data for baltimore: from 2010-01-01 to 2010-01-31
Time elapsed (hh:mm:ss.ms) 0:00:02.725096
Currently retrieving data for baltimore: from 2010-02-01 to 2010-02-28
Time elapsed (hh:mm:ss.ms) 0:00:05.358189
Currently retrieving data for baltimore: from 2010-03-01 to 2010-03-31
Time elapsed (hh:mm:ss.ms) 0:00:07.952349
Currently retrieving data for baltimore: from 2010-04-01 to 2010-04-30
Time elapsed (hh:mm:ss.ms) 0:00:10.826197
Currently retrieving data for baltimore: from 2010-05-01 to 2010-05-31
Time elapsed (hh:mm:ss.ms) 0:00:13.539214
Currently retrieving data for baltimore: from 2010-06-01 to 2010-06-30
Time elapsed (hh:mm:ss.ms) 0:00:16.126802
Currently retrieving data for baltimore: from 2010-07-01 to 2010-07-31
Time elapsed (hh:mm:ss.ms) 0:00:18.797743
Currently retrieving data for baltimore: from 2010-08-01 to 2010-08-31
Time elapsed (hh:mm:ss.ms) 0:00:21.673575
Currently retrieving data for baltimore: from 2010-09-01 to 2010-09-30
Time elapsed (hh:mm:ss.ms) 0:00:24.444852
Currently retrieving data for baltimore: from 2010-10-01 to 2010-10-31
Time elapsed (hh:mm:ss.ms) 0:00:27.338342
Currently retrieving data for baltimore: from 2010-11-01 to 2010-11-30
Time elapsed (hh:mm:ss.ms) 0:00:29.892631
Currently retrieving data for baltimore: from 2010-12-01 to 2010-12-31
Time elapsed (hh:mm:ss.ms) 0:00:32.585080
Currently retrieving data for baltimore: from 2011-01-01 to 2011-01-31
Time elapsed (hh:mm:ss.ms) 0:00:35.958322
Currently retrieving data for baltimore: from 2011-02-01 to 2011-02-28
Time elapsed (hh:mm:ss.ms) 0:00:38.881328
Currently retrieving data for baltimore: from 2011-03-01 to 2011-03-31
Time elapsed (hh:mm:ss.ms) 0:00:42.072226
Currently retrieving data for baltimore: from 2011-04-01 to 2011-04-30
Time elapsed (hh:mm:ss.ms) 0:00:45.019180
Currently retrieving data for baltimore: from 2011-05-01 to 2011-05-31
Time elapsed (hh:mm:ss.ms) 0:00:48.594447
Currently retrieving data for baltimore: from 2011-06-01 to 2011-06-30
Time elapsed (hh:mm:ss.ms) 0:00:51.676783
Currently retrieving data for baltimore: from 2011-07-01 to 2011-07-31
Time elapsed (hh:mm:ss.ms) 0:00:54.746276
Currently retrieving data for baltimore: from 2011-08-01 to 2011-08-31
Time elapsed (hh:mm:ss.ms) 0:00:57.994185
Currently retrieving data for baltimore: from 2011-09-01 to 2011-09-30
Time elapsed (hh:mm:ss.ms) 0:01:00.950435
Currently retrieving data for baltimore: from 2011-10-01 to 2011-10-31
Time elapsed (hh:mm:ss.ms) 0:01:04.016289
Currently retrieving data for baltimore: from 2011-11-01 to 2011-11-30
Time elapsed (hh:mm:ss.ms) 0:01:06.803275
Currently retrieving data for baltimore: from 2011-12-01 to 2011-12-31
Time elapsed (hh:mm:ss.ms) 0:01:09.652951
Currently retrieving data for baltimore: from 2012-01-01 to 2012-01-31
Time elapsed (hh:mm:ss.ms) 0:01:12.505564
Currently retrieving data for baltimore: from 2012-02-01 to 2012-02-29
Time elapsed (hh:mm:ss.ms) 0:01:15.191097
Currently retrieving data for baltimore: from 2012-03-01 to 2012-03-31
Time elapsed (hh:mm:ss.ms) 0:01:18.152572
Currently retrieving data for baltimore: from 2012-04-01 to 2012-04-30
Time elapsed (hh:mm:ss.ms) 0:01:21.035883
Currently retrieving data for baltimore: from 2012-05-01 to 2012-05-31
Time elapsed (hh:mm:ss.ms) 0:01:24.056884
Currently retrieving data for baltimore: from 2012-06-01 to 2012-06-30
Time elapsed (hh:mm:ss.ms) 0:01:27.036425
Currently retrieving data for baltimore: from 2012-07-01 to 2012-07-31
Time elapsed (hh:mm:ss.ms) 0:01:29.898146
Currently retrieving data for baltimore: from 2012-08-01 to 2012-08-31
Time elapsed (hh:mm:ss.ms) 0:01:32.829675
Currently retrieving data for baltimore: from 2012-09-01 to 2012-09-30
Time elapsed (hh:mm:ss.ms) 0:01:35.659372
Currently retrieving data for baltimore: from 2012-10-01 to 2012-10-31
Time elapsed (hh:mm:ss.ms) 0:01:38.532438
Currently retrieving data for baltimore: from 2012-11-01 to 2012-11-30
Time elapsed (hh:mm:ss.ms) 0:01:41.245193
Currently retrieving data for baltimore: from 2012-12-01 to 2012-12-31
Time elapsed (hh:mm:ss.ms) 0:01:44.176567
Currently retrieving data for baltimore: from 2013-01-01 to 2013-01-31
Time elapsed (hh:mm:ss.ms) 0:01:47.227198
Currently retrieving data for baltimore: from 2013-02-01 to 2013-02-28
Time elapsed (hh:mm:ss.ms) 0:01:49.935557
Currently retrieving data for baltimore: from 2013-03-01 to 2013-03-31
Time elapsed (hh:mm:ss.ms) 0:01:53.077737
Currently retrieving data for baltimore: from 2013-04-01 to 2013-04-30
Time elapsed (hh:mm:ss.ms) 0:01:55.915458
Currently retrieving data for baltimore: from 2013-05-01 to 2013-05-31
Time elapsed (hh:mm:ss.ms) 0:01:58.922312
Currently retrieving data for baltimore: from 2013-06-01 to 2013-06-30
Time elapsed (hh:mm:ss.ms) 0:02:01.687933
Currently retrieving data for baltimore: from 2013-07-01 to 2013-07-31
Time elapsed (hh:mm:ss.ms) 0:02:04.586169
Currently retrieving data for baltimore: from 2013-08-01 to 2013-08-31
Time elapsed (hh:mm:ss.ms) 0:02:07.450974
Currently retrieving data for baltimore: from 2013-09-01 to 2013-09-30
Time elapsed (hh:mm:ss.ms) 0:02:10.283085
Currently retrieving data for baltimore: from 2013-10-01 to 2013-10-31
Time elapsed (hh:mm:ss.ms) 0:02:13.191896
Currently retrieving data for baltimore: from 2013-11-01 to 2013-11-30
Time elapsed (hh:mm:ss.ms) 0:02:15.898105
Currently retrieving data for baltimore: from 2013-12-01 to 2013-12-31
Time elapsed (hh:mm:ss.ms) 0:02:18.736282
Currently retrieving data for baltimore: from 2014-01-01 to 2014-01-31
Time elapsed (hh:mm:ss.ms) 0:02:21.722907
Currently retrieving data for baltimore: from 2014-02-01 to 2014-02-28
Time elapsed (hh:mm:ss.ms) 0:02:24.521686
Currently retrieving data for baltimore: from 2014-03-01 to 2014-03-31
Time elapsed (hh:mm:ss.ms) 0:02:27.452068
Currently retrieving data for baltimore: from 2014-04-01 to 2014-04-30
Time elapsed (hh:mm:ss.ms) 0:02:30.216825
Currently retrieving data for baltimore: from 2014-05-01 to 2014-05-31
Time elapsed (hh:mm:ss.ms) 0:02:33.161501
Currently retrieving data for baltimore: from 2014-06-01 to 2014-06-30
Time elapsed (hh:mm:ss.ms) 0:02:35.899624
Currently retrieving data for baltimore: from 2014-07-01 to 2014-07-31
Time elapsed (hh:mm:ss.ms) 0:02:38.742166
Currently retrieving data for baltimore: from 2014-08-01 to 2014-08-31
Time elapsed (hh:mm:ss.ms) 0:02:41.605360
Currently retrieving data for baltimore: from 2014-09-01 to 2014-09-30
Time elapsed (hh:mm:ss.ms) 0:02:44.370601
Currently retrieving data for baltimore: from 2014-10-01 to 2014-10-31
Time elapsed (hh:mm:ss.ms) 0:02:47.402161
Currently retrieving data for baltimore: from 2014-11-01 to 2014-11-30
Time elapsed (hh:mm:ss.ms) 0:02:50.157137
Currently retrieving data for baltimore: from 2014-12-01 to 2014-12-31
Time elapsed (hh:mm:ss.ms) 0:02:53.033904
Currently retrieving data for baltimore: from 2015-01-01 to 2015-01-31
Time elapsed (hh:mm:ss.ms) 0:02:56.223553
Currently retrieving data for baltimore: from 2015-02-01 to 2015-02-28
Time elapsed (hh:mm:ss.ms) 0:02:58.966599
Currently retrieving data for baltimore: from 2015-03-01 to 2015-03-31
Time elapsed (hh:mm:ss.ms) 0:03:02.095852
Currently retrieving data for baltimore: from 2015-04-01 to 2015-04-30
Time elapsed (hh:mm:ss.ms) 0:03:04.813357
Currently retrieving data for baltimore: from 2015-05-01 to 2015-05-31
Time elapsed (hh:mm:ss.ms) 0:03:07.691569
Currently retrieving data for baltimore: from 2015-06-01 to 2015-06-30
Time elapsed (hh:mm:ss.ms) 0:03:10.609799
Currently retrieving data for baltimore: from 2015-07-01 to 2015-07-31
Time elapsed (hh:mm:ss.ms) 0:03:13.588335
Currently retrieving data for baltimore: from 2015-08-01 to 2015-08-31
Time elapsed (hh:mm:ss.ms) 0:03:17.890075
Currently retrieving data for baltimore: from 2015-09-01 to 2015-09-30
Time elapsed (hh:mm:ss.ms) 0:03:20.610634
Currently retrieving data for baltimore: from 2015-10-01 to 2015-10-31
Time elapsed (hh:mm:ss.ms) 0:03:23.491474
Currently retrieving data for baltimore: from 2015-11-01 to 2015-11-30
Time elapsed (hh:mm:ss.ms) 0:03:26.430492
Currently retrieving data for baltimore: from 2015-12-01 to 2015-12-31
Time elapsed (hh:mm:ss.ms) 0:03:29.398632
Currently retrieving data for baltimore: from 2016-01-01 to 2016-01-31
Time elapsed (hh:mm:ss.ms) 0:03:32.706989
Currently retrieving data for baltimore: from 2016-02-01 to 2016-02-29
Time elapsed (hh:mm:ss.ms) 0:03:35.450333
Currently retrieving data for baltimore: from 2016-03-01 to 2016-03-31
Time elapsed (hh:mm:ss.ms) 0:03:38.487704
Currently retrieving data for baltimore: from 2016-04-01 to 2016-04-30
Time elapsed (hh:mm:ss.ms) 0:03:41.292206
Currently retrieving data for baltimore: from 2016-05-01 to 2016-05-31
Time elapsed (hh:mm:ss.ms) 0:03:44.169576
Currently retrieving data for baltimore: from 2016-06-01 to 2016-06-30
Time elapsed (hh:mm:ss.ms) 0:03:46.893080
Currently retrieving data for baltimore: from 2016-07-01 to 2016-07-31
Time elapsed (hh:mm:ss.ms) 0:03:49.820599
Currently retrieving data for baltimore: from 2016-08-01 to 2016-08-31
Time elapsed (hh:mm:ss.ms) 0:03:52.730971
Currently retrieving data for baltimore: from 2016-09-01 to 2016-09-30
Time elapsed (hh:mm:ss.ms) 0:03:55.702817
Currently retrieving data for baltimore: from 2016-10-01 to 2016-10-31
Time elapsed (hh:mm:ss.ms) 0:03:58.586913
Currently retrieving data for baltimore: from 2016-11-01 to 2016-11-30
Time elapsed (hh:mm:ss.ms) 0:04:01.314962
Currently retrieving data for baltimore: from 2016-12-01 to 2016-12-31
Time elapsed (hh:mm:ss.ms) 0:04:04.174967
Currently retrieving data for baltimore: from 2017-01-01 to 2017-01-31
Time elapsed (hh:mm:ss.ms) 0:04:07.142228
Currently retrieving data for baltimore: from 2017-02-01 to 2017-02-28
Time elapsed (hh:mm:ss.ms) 0:04:09.670510
Currently retrieving data for baltimore: from 2017-03-01 to 2017-03-31
Time elapsed (hh:mm:ss.ms) 0:04:12.456159
Currently retrieving data for baltimore: from 2017-04-01 to 2017-04-30
Time elapsed (hh:mm:ss.ms) 0:04:15.070922
Currently retrieving data for baltimore: from 2017-05-01 to 2017-05-31
Time elapsed (hh:mm:ss.ms) 0:04:17.850834
Currently retrieving data for baltimore: from 2017-06-01 to 2017-06-30
Time elapsed (hh:mm:ss.ms) 0:04:20.703090
Currently retrieving data for baltimore: from 2017-07-01 to 2017-07-31
Time elapsed (hh:mm:ss.ms) 0:04:23.455860
Currently retrieving data for baltimore: from 2017-08-01 to 2017-08-31
Time elapsed (hh:mm:ss.ms) 0:04:26.206098
Currently retrieving data for baltimore: from 2017-09-01 to 2017-09-30
Time elapsed (hh:mm:ss.ms) 0:04:28.803885
Currently retrieving data for baltimore: from 2017-10-01 to 2017-10-31
Time elapsed (hh:mm:ss.ms) 0:04:31.571908
Currently retrieving data for baltimore: from 2017-11-01 to 2017-11-30
Time elapsed (hh:mm:ss.ms) 0:04:34.162590
Currently retrieving data for baltimore: from 2017-12-01 to 2017-12-31
Time elapsed (hh:mm:ss.ms) 0:04:36.886778
Currently retrieving data for baltimore: from 2018-01-01 to 2018-01-31
Time elapsed (hh:mm:ss.ms) 0:04:39.720939
Currently retrieving data for baltimore: from 2018-02-01 to 2018-02-28
Time elapsed (hh:mm:ss.ms) 0:04:42.240958
Currently retrieving data for baltimore: from 2018-03-01 to 2018-03-31
Time elapsed (hh:mm:ss.ms) 0:04:45.006671
Currently retrieving data for baltimore: from 2018-04-01 to 2018-04-30
Time elapsed (hh:mm:ss.ms) 0:04:47.618661
Currently retrieving data for baltimore: from 2018-05-01 to 2018-05-31
Time elapsed (hh:mm:ss.ms) 0:04:50.376255
Currently retrieving data for baltimore: from 2018-06-01 to 2018-06-30
Time elapsed (hh:mm:ss.ms) 0:04:53.025474
Currently retrieving data for baltimore: from 2018-07-01 to 2018-07-31
Time elapsed (hh:mm:ss.ms) 0:04:55.793815
Currently retrieving data for baltimore: from 2018-08-01 to 2018-08-31
Time elapsed (hh:mm:ss.ms) 0:04:58.544079
Currently retrieving data for baltimore: from 2018-09-01 to 2018-09-30
Time elapsed (hh:mm:ss.ms) 0:05:01.159046
Currently retrieving data for baltimore: from 2018-10-01 to 2018-10-31
Time elapsed (hh:mm:ss.ms) 0:05:03.983465
Currently retrieving data for baltimore: from 2018-11-01 to 2018-11-30
Time elapsed (hh:mm:ss.ms) 0:05:06.617425
Currently retrieving data for baltimore: from 2018-12-01 to 2018-12-31
Time elapsed (hh:mm:ss.ms) 0:05:09.368797
Currently retrieving data for baltimore: from 2019-01-01 to 2019-01-31
Time elapsed (hh:mm:ss.ms) 0:05:12.094495
Currently retrieving data for baltimore: from 2019-02-01 to 2019-02-28
Time elapsed (hh:mm:ss.ms) 0:05:14.584961
Currently retrieving data for baltimore: from 2019-03-01 to 2019-03-31
Time elapsed (hh:mm:ss.ms) 0:05:17.513764
Currently retrieving data for baltimore: from 2019-04-01 to 2019-04-30
Time elapsed (hh:mm:ss.ms) 0:05:20.093212
Currently retrieving data for baltimore: from 2019-05-01 to 2019-05-31
Time elapsed (hh:mm:ss.ms) 0:05:22.823283
Currently retrieving data for baltimore: from 2019-06-01 to 2019-06-30
Time elapsed (hh:mm:ss.ms) 0:05:25.434861
Currently retrieving data for baltimore: from 2019-07-01 to 2019-07-31
Time elapsed (hh:mm:ss.ms) 0:05:28.177242
Currently retrieving data for baltimore: from 2019-08-01 to 2019-08-31
Time elapsed (hh:mm:ss.ms) 0:05:30.917774
Currently retrieving data for baltimore: from 2019-09-01 to 2019-09-30
Time elapsed (hh:mm:ss.ms) 0:05:33.517402
Currently retrieving data for baltimore: from 2019-10-01 to 2019-10-31
Time elapsed (hh:mm:ss.ms) 0:05:36.238085
Currently retrieving data for baltimore: from 2019-11-01 to 2019-11-30
Time elapsed (hh:mm:ss.ms) 0:05:38.834954
Currently retrieving data for baltimore: from 2019-12-01 to 2019-12-31
Time elapsed (hh:mm:ss.ms) 0:05:41.594029
Currently retrieving data for baltimore: from 2020-01-01 to 2020-01-31
Time elapsed (hh:mm:ss.ms) 0:05:44.341007
Currently retrieving data for baltimore: from 2020-02-01 to 2020-02-29
Time elapsed (hh:mm:ss.ms) 0:05:46.878360
Currently retrieving data for baltimore: from 2020-03-01 to 2020-03-31
Time elapsed (hh:mm:ss.ms) 0:05:49.644826
Currently retrieving data for baltimore: from 2020-04-01 to 2020-04-30
Time elapsed (hh:mm:ss.ms) 0:05:52.304699
Currently retrieving data for baltimore: from 2020-05-01 to 2020-05-31
Time elapsed (hh:mm:ss.ms) 0:05:55.049671
Currently retrieving data for baltimore: from 2020-06-01 to 2020-06-01
Time elapsed (hh:mm:ss.ms) 0:05:55.517143


export baltimore completed!

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,moon_illumination,moonrise,moonset,sunrise,...,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph,location
0,2010-01-01 00:00:00,0,0,0.0,8.7,1,100,06:11 PM,08:10 AM,07:27 AM,...,6,75,97,0.0,1016,-1,2,346,4,baltimore
1,2010-01-01 03:00:00,0,0,0.0,8.7,1,100,06:11 PM,08:10 AM,07:27 AM,...,5,23,96,0.0,1015,0,2,301,3,baltimore
2,2010-01-01 06:00:00,0,0,0.0,8.7,1,100,06:11 PM,08:10 AM,07:27 AM,...,11,20,95,0.0,1015,-2,2,302,5,baltimore
3,2010-01-01 09:00:00,0,0,0.0,8.7,1,100,06:11 PM,08:10 AM,07:27 AM,...,27,18,90,0.0,1015,2,10,311,17,baltimore
4,2010-01-01 12:00:00,0,0,0.0,8.7,1,100,06:11 PM,08:10 AM,07:27 AM,...,11,51,89,0.0,1013,5,10,306,9,baltimore

             date_time  humidity  pressure  cloudcover
0  2010-01-01 00:00:00        97      1016          75
1  2010-01-01 03:00:00        96      1015          23
2  2010-01-01 06:00:00        95      1015          20
3  2010-01-01 09:00:00        90      1015          18
4  2010-01-01 12:00:00        89      1013          51

             date_time  temperature  humidity  pressure  cloudcover
0  2010-01-01 00:00:00         30.2        97      1016          75
1  2010-01-01 03:00:00         32.0        96      1015          23
2  2010-01-01 06:00:00         28.4        95      1015          20
3  2010-01-01 09:00:00         35.6        90      1015          18
4  2010-01-01 12:00:00         41.0        89      1013          51